// Copyright 2025 Specter Ops, Inc.
//
// Licensed under the Apache License, Version 2.0
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package dawgs

import (
	"context"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"

	"github.com/specterops/dawgs/graph"
	"github.com/specterops/dawgs/query"
	neo4jquery "github.com/specterops/dawgs/query/neo4j"
	"github.com/specterops/dawgs/util/size"
)

// reVarKindInWhere matches "var:Kind" label-check patterns inside WHERE clauses.
// These must be excluded from MATCH patterns (not inside brackets/parens that are
// part of the MATCH section), so only the portion after the WHERE keyword is scanned.
var reVarKindInWhere = regexp.MustCompile(`(\w+):([\w` + "`" + `]+)`)

// reMultiTypeRel matches relationship patterns with pipe-separated types:
// [varname:TypeA|TypeB|...] or [:TypeA|TypeB|...]
// Groups: 1=varname (may be empty), 2=pipe-separated types
// NOTE: Does NOT match variable-length patterns like [r:Type1|Type2*] because
// rewriting those to WHERE type(r) IN [...] is semantically wrong for paths.
var reMultiTypeRel = regexp.MustCompile(`\[(\w*):([\w` + "`" + `]+(?:\|[\w` + "`" + `]+)+)\]`)

// reInParam matches "IN $paramName" patterns where kglite expects IN [literal list].
var reInParam = regexp.MustCompile(`(?i)\bIN\s+\$(\w+)`)

// rewriteForKglite transforms Cypher generated by the neo4j query builder into
// kglite-compatible Cypher. Handles three incompatibilities:
//  1. kglite does not support n:Kind label checks in WHERE clauses.
//  2. kglite does not support pipe-separated relationship types [:TypeA|TypeB].
//  3. kglite does not support IN $param (parameterized lists).
func rewriteForKglite(cypher string, params map[string]any) string {
	cypher = rewriteMultiTypeRel(cypher)
	cypher = rewriteLabelWhere(cypher)
	cypher = rewriteInParam(cypher, params)
	return cypher
}

// rewriteInParam expands "IN $paramName" into "IN [val1, val2, ...]" by
// inlining the parameter value. kglite's Cypher parser requires a literal
// list after IN, not a parameter reference.
func rewriteInParam(cypher string, params map[string]any) string {
	return reInParam.ReplaceAllStringFunc(cypher, func(m string) string {
		sub := reInParam.FindStringSubmatch(m)
		paramName := sub[1]

		val, ok := params[paramName]
		if !ok {
			return m // parameter not found, leave unchanged
		}

		rv := reflect.ValueOf(val)
		if rv.Kind() != reflect.Slice && rv.Kind() != reflect.Array {
			return m // not a list, leave unchanged
		}

		elems := make([]string, rv.Len())
		for i := 0; i < rv.Len(); i++ {
			v := rv.Index(i).Interface()
			switch v.(type) {
			case string:
				elems[i] = fmt.Sprintf("'%s'", v)
			default:
				elems[i] = fmt.Sprintf("%v", v)
			}
		}

		// Remove the consumed parameter
		delete(params, paramName)

		return fmt.Sprintf("IN [%s]", strings.Join(elems, ", "))
	})
}

// rewriteMultiTypeRel rewrites [:TypeA|TypeB] relationship patterns into
// MATCH (a)-[_kgrt0]->(b) WHERE type(_kgrt0) IN ['TypeA', 'TypeB'].
func rewriteMultiTypeRel(cypher string) string {
	counter := 0
	var conditions []string

	result := reMultiTypeRel.ReplaceAllStringFunc(cypher, func(m string) string {
		sub := reMultiTypeRel.FindStringSubmatch(m)
		varName, typesStr := sub[1], sub[2]

		// Strip backticks from type names
		types := strings.Split(typesStr, "|")
		for i, t := range types {
			types[i] = strings.Trim(t, "`")
		}

		if varName == "" {
			varName = fmt.Sprintf("_kgrt%d", counter)
			counter++
		}

		quoted := make([]string, len(types))
		for i, t := range types {
			quoted[i] = fmt.Sprintf("'%s'", t)
		}
		conditions = append(conditions, fmt.Sprintf("type(%s) IN [%s]", varName, strings.Join(quoted, ", ")))
		return fmt.Sprintf("[%s]", varName)
	})

	if len(conditions) == 0 {
		return result
	}

	condStr := strings.Join(conditions, " AND ")
	lower := strings.ToLower(result)

	// Insert into existing WHERE clause
	if idx := strings.Index(lower, " where "); idx >= 0 {
		return result[:idx+7] + condStr + " AND " + result[idx+7:]
	}

	// Add WHERE before the first RETURN/WITH/ORDER/LIMIT/SKIP/UNION
	for _, kw := range []string{" return ", " with ", " order ", " limit ", " skip ", " union "} {
		if idx := strings.Index(lower, kw); idx >= 0 {
			return result[:idx] + " WHERE " + condStr + result[idx:]
		}
	}

	return result + " WHERE " + condStr
}

// rewriteLabelWhere rewrites "var:Kind" label checks in WHERE clauses into
// a check against both the __kinds property and labels() function.
// kglite does not support the n:Kind syntax in WHERE expressions at all —
// it only works in MATCH patterns. Secondary labels (e.g. Domain, Entity)
// are stored in the __kinds property, while the primary label is returned
// by labels(). We check both to handle all cases.
func rewriteLabelWhere(cypher string) string {
	lower := strings.ToLower(cypher)
	whereIdx := strings.Index(lower, " where ")
	if whereIdx < 0 {
		return cypher
	}

	matchPart := cypher[:whereIdx+1]     // everything up to (and including) the space before WHERE
	whereOnward := cypher[whereIdx+1:]   // "where ..." and everything after

	// Replace all var:Kind occurrences in the WHERE clause and beyond.
	// The MATCH pattern (before WHERE) is left untouched.
	whereOnward = reVarKindInWhere.ReplaceAllStringFunc(whereOnward, func(m string) string {
		sub := reVarKindInWhere.FindStringSubmatch(m)
		varName, kind := sub[1], sub[2]
		kind = strings.Trim(kind, "`")
		return fmt.Sprintf(`(%s.__kinds CONTAINS '"%s"' OR labels(%s) CONTAINS '"%s"')`, varName, kind, varName, kind)
	})

	return matchPart + whereOnward
}

// Transaction implements graph.Transaction using kglite.
type Transaction struct {
	ctx      context.Context
	driver   *Driver
	readOnly bool
}

func (t *Transaction) WithGraph(_ graph.Graph) graph.Transaction {
	return t
}

func (t *Transaction) GraphQueryMemoryLimit() size.Size {
	return graphQueryMemoryLimit()
}

func (t *Transaction) Commit() error {
	return nil
}

// Raw executes a raw Cypher query and returns a graph.Result.
func (t *Transaction) Raw(cypher string, parameters map[string]any) graph.Result {
	rewritten := rewriteForKglite(cypher, parameters)
	if cypher != rewritten {
		fmt.Printf("KGLITE-REWRITE:\n  from: %s\n  to:   %s\n\n", cypher, rewritten)
	}
	start := time.Now()
	result, err := t.driver.kg.Cypher(rewritten, parameters)
	if ProfilingEnabled() {
		recordQuery(rewritten, time.Since(start))
	}
	if err != nil {
		fmt.Printf("KGLITE-DEBUG FAIL:\n  original: %s\n  rewritten: %s\n  err: %v\n\n", cypher, rewritten, err)
		return newErrorResult(err)
	}
	// Convert JSON values in rows to DAWGS types
	for i, row := range result.Rows {
		for j, v := range row {
			result.Rows[i][j] = convertValue(v)
		}
	}
	return newResult(result)
}

// Query is an alias for Raw.
func (t *Transaction) Query(cypher string, parameters map[string]any) graph.Result {
	return t.Raw(cypher, parameters)
}

// Nodes returns a NodeQuery scoped to this transaction.
func (t *Transaction) Nodes() graph.NodeQuery {
	return &nodeQuery{
		ctx:          t.ctx,
		tx:           t,
		queryBuilder: neo4jquery.NewEmptyQueryBuilder(),
	}
}

// Relationships returns a RelationshipQuery scoped to this transaction.
func (t *Transaction) Relationships() graph.RelationshipQuery {
	return &relQuery{
		ctx:          t.ctx,
		tx:           t,
		queryBuilder: neo4jquery.NewEmptyQueryBuilder(),
	}
}

// CreateNode creates a new node.
func (t *Transaction) CreateNode(properties *graph.Properties, kinds ...graph.Kind) (*graph.Node, error) {
	if len(kinds) == 0 {
		return nil, fmt.Errorf("kglite: CreateNode requires at least one kind")
	}

	// Build: CREATE (n:`Kind` {key: $p_key, ...}) RETURN n
	var propsMap map[string]any
	if properties != nil {
		propsMap = make(map[string]any, len(properties.Map)+1)
		for k, v := range properties.Map {
			propsMap[k] = v
		}
	} else {
		propsMap = make(map[string]any, 1)
	}
	// Store all kinds as __kinds so secondary labels are queryable
	if len(kinds) > 1 {
		allKinds := make([]string, len(kinds))
		for i, k := range kinds {
			allKinds[i] = k.String()
		}
		propsMap["__kinds"] = allKinds
	}
	pattern, params := propsPattern("p_", propsMap)

	result, err := t.driver.kg.Cypher(
		fmt.Sprintf("CREATE (n:%s %s) RETURN n", quoteIdent(kinds[0].String()), pattern),
		params,
	)
	if err != nil {
		return nil, fmt.Errorf("kglite: CreateNode: %w", err)
	}
	if len(result.Rows) == 0 || len(result.Rows[0]) == 0 {
		return nil, fmt.Errorf("kglite: CreateNode: no result returned")
	}

	v := convertValue(result.Rows[0][0])
	if node, ok := v.(*graph.Node); ok {
		// Add additional kinds
		for _, k := range kinds[1:] {
			if k != nil {
				node.Kinds = node.Kinds.Add(k)
			}
		}
		return node, nil
	}
	return nil, fmt.Errorf("kglite: CreateNode: unexpected result type %T", v)
}

// UpdateNode updates a node's properties and kinds.
func (t *Transaction) UpdateNode(node *graph.Node) error {
	if node.Properties == nil {
		node.Properties = graph.NewProperties()
	}

	// Ensure __kinds is set when node has multiple kinds
	if len(node.Kinds) > 1 {
		allKinds := make([]string, len(node.Kinds))
		for i, k := range node.Kinds {
			allKinds[i] = k.String()
		}
		node.Properties.Set("__kinds", allKinds)
	}

	modified := node.Properties.ModifiedProperties()
	if len(modified) == 0 {
		return nil
	}

	qb := neo4jquery.NewEmptyQueryBuilder()
	qb.Apply(query.Where(query.Equals(query.NodeID(), node.ID)))
	qb.Apply(query.Updatef(func() graph.Criteria {
		return query.SetProperties(query.Node(), modified)
	}))

	if err := qb.Prepare(); err != nil {
		return err
	}
	cypher, err := qb.Render()
	if err != nil {
		return err
	}
	_, err = t.driver.kg.Cypher(cypher, qb.Parameters)
	return err
}

// CreateRelationshipByIDs creates a relationship between two nodes by their IDs.
func (t *Transaction) CreateRelationshipByIDs(startNodeID, endNodeID graph.ID, kind graph.Kind, properties *graph.Properties) (*graph.Relationship, error) {
	kindStr := kind.String()
	if kindStr == "" {
		return nil, fmt.Errorf("kglite: CreateRelationshipByIDs: relationship kind cannot be empty")
	}

	var propsMap map[string]any
	if properties != nil {
		propsMap = properties.Map
	} else {
		propsMap = map[string]any{}
	}

	baseParams := map[string]any{
		"start_id": uint64(startNodeID),
		"end_id":   uint64(endNodeID),
	}
	relPattern, propParams := propsPattern("rp_", propsMap)

	cypher := fmt.Sprintf(
		`MATCH (s) WHERE id(s) = $start_id MATCH (e) WHERE id(e) = $end_id CREATE (s)-[r:%s %s]->(e) RETURN r`,
		quoteIdent(kindStr), relPattern,
	)
	result, err := t.driver.kg.Cypher(cypher, mergeParams(baseParams, propParams))
	if err != nil {
		return nil, fmt.Errorf("kglite: CreateRelationshipByIDs: %w", err)
	}
	if len(result.Rows) == 0 {
		return nil, fmt.Errorf("kglite: CreateRelationshipByIDs: no result (nodes not found)")
	}
	// kglite returns the edge type string for RETURN r, not an edge object.
	// Construct the relationship from the known inputs; edge ID will be 0.
	return graph.NewRelationship(0, startNodeID, endNodeID, properties, kind), nil
}

// UpdateRelationship updates a relationship's properties.
func (t *Transaction) UpdateRelationship(relationship *graph.Relationship) error {
	if relationship.Properties == nil {
		return nil
	}
	modified := relationship.Properties.ModifiedProperties()
	if len(modified) == 0 {
		return nil
	}

	qb := neo4jquery.NewEmptyQueryBuilder()
	qb.Apply(query.Where(query.Equals(query.RelationshipID(), relationship.ID)))
	qb.Apply(query.Updatef(func() graph.Criteria {
		return query.SetProperties(query.Relationship(), modified)
	}))

	if err := qb.Prepare(); err != nil {
		return err
	}
	cypher, err := qb.Render()
	if err != nil {
		return err
	}
	_, err = t.driver.kg.Cypher(cypher, qb.Parameters)
	return err
}
